- name: this is my first palybook  
  hosts: node1
  gather_facts: false
  user: ec2-user
  become: true
  become_method: sudo 
  tasks: 
    -name: install httpd package
     yum: 
       name: httpd
       state: latest

    - name: copy a1 file to a3
      copy: 
       src: /home/ec2-user/a1
       dest: /a3
