- name: this is my first palybook  
  hosts: node2
  gather_facts: false
  user: ec2-user
  become: true
  become_method: sudo 
  tasks: 
    - name: install httpd package
      yum: 
        name: httpd
        state: latest
        
    - name: copy /etc/fstab into /tmp
      copy: 
          src: /etc/fstab
          dest: /tmp
          mode: 0777
          owner: ec2-user

- name: this is secound play
  hosts: node1
  gather_facts: false
  tasks:
      - name : copy
        copy:
          src: /etc/motd 
          dest: /tmp
