- name: example of playbook level variable
  hosts: node1 
  vars:
    web_root: /home/ec2-user/kush123 
    app: krnetwork-2.0.war
  tasks:
    - name: create web root
      file:
         name: "{{ web_root }}"
         state:  directory
    - debug:
           msg: "this is {{ web_root }} for deplopment"

    - name: copy  "{{ app }} " into "{{ web_root }}"
      copy:
         src: "{{ app }}"
         dest: "{{ web_root }}"
 
