- name: example of register variable
  hosts: node1 
  tasks: 
     - stat: 
         path: /var/www/html/index.html
       register: xyz

     - name: create file if does not exits
       copy: 
          content: "hello from {{ ansible_hostname }}"
          dest: /var/www/html/index.html 
       when: xyz.stat.exists == false

     - name: append diffrent content if file exists
       lineinfile:
                line: "Happy New year"
                dest: /var/www/html/index.html
       when: xyz.stat.exists == true
      
