- name: example of register variable
  hosts: node1 
  tasks: 
     - stat: 
         path: /home/ec2-user/kks
       register: xyz

     - name: create file if does not exits
       copy: 
          content: "hello from {{ ansible_hostname }}"
          dest: /home/ec2-user/kks
       when: xyz.stat.exists == false

     - name: append diffrent content if file exists
       lineinfile:
                line: "Happy New year"
                dest: /home/ec2-user/kks
       when: xyz.stat.exists == true
      
